# Generated by Django 2.0.2 on 2018-02-28 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('dob', models.DateField(blank=True)),
                ('homePhone', models.CharField(max_length=250)),
                ('personalPhone', models.CharField(max_length=250)),
                ('emergencyContact', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('ppsn', models.CharField(max_length=250)),
                ('maritalStatus', models.CharField(max_length=250)),
                ('employment', models.BooleanField()),
                ('personalPic', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
