# Generated by Django 2.0.2 on 2018-03-07 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180307_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doc_email',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doc_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doc_num',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='illnesses',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_visit',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medicine',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
