# Generated by Django 2.0.2 on 2018-03-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20180307_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_visit',
            field=models.DateField(blank=True),
        ),
    ]
