# Generated by Django 2.0.2 on 2018-03-08 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20180307_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doc_email1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doc_name1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doc_num1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_visit1',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
