# Generated by Django 2.0.2 on 2018-03-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20180308_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='doc_email',
            new_name='curr_doc_email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='doc_email1',
            new_name='curr_doc_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='doc_name',
            new_name='curr_doc_num',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_visit',
            new_name='curr_last_visit',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='doc_name1',
            new_name='prev_doc_email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='doc_num',
            new_name='prev_doc_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='doc_num1',
            new_name='prev_doc_num',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_visit1',
            new_name='prev_last_visit',
        ),
    ]
