# Generated by Django 2.0.2 on 2018-02-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('dob', models.CharField(max_length=250)),
                ('homePhone', models.CharField(max_length=250)),
                ('personalPhone', models.CharField(max_length=250)),
                ('emergencyContact', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('ppsn', models.CharField(max_length=250)),
                ('maritalStatus', models.CharField(max_length=250)),
                ('employment', models.CharField(max_length=250)),
                ('personalPic', models.CharField(max_length=1000)),
            ],
        ),
    ]
