# Generated by Django 2.0.2 on 2018-02-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinfo',
            name='generalInfo',
        ),
        migrations.DeleteModel(
            name='HealthInfo',
        ),
    ]
