# Generated by Django 2.0.2 on 2018-03-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralInfo',
            new_name='UserProfile',
        ),
    ]
